# Generated by Django 2.2.6 on 2020-04-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=50)),
                ('inner_ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
    ]
